"""Canonical, pure MODE:P vNext domain schemas (architecture v2.2)."""

from .artifact import (
    ArtifactEnvelope,
    ArtifactKind,
    DomainValidationError,
    SourceRef,
    ValidationStatus,
)
from .blocking import (
    BlockingBeat,
    BlockingBeatDraft,
    BlockingCommit,
    BlockingDraft,
)
from .decisions import (
    DecisionBasis,
    DecisionDraft,
    DirectorDecision,
    VisualCurvePoint,
    VisualCurvePointDraft,
)
from .direction import EpisodeDirectionDraft, SceneIntentDraft
from .facts import FactKind, FactRegistry, FactSemantic, ScriptFact
from .ids import IdFactory
from .evidence import (
    DPReviewVerdict,
    DeterministicGateResult,
    IndependentDPReviewResult,
    MediaEvidence,
    OwnerApprovalDecision,
    OwnerApprovalRecord,
)
from .knowledge import (
    KnowledgeCandidateRecord,
    KnowledgeCapabilityScope,
    KnowledgeCapsuleV2,
    KnowledgeDecisionEntry,
    KnowledgeDecisionView,
    KnowledgeSnapshot,
    KnowledgeStage,
)
from .projection import ProjectionAST, ProjectionManifest, ProjectionNode
from .time import (
    CanonicalTimeline,
    GenerationSegmentTimeline,
    TickRange,
    TimelinePlacement,
)
from .vec import (
    AudioEvent,
    ExecutionDesignDraft,
    GenerationSegment,
    ReferenceRequirement,
    ShotBoundary,
    ShotDesignDraft,
    StoryboardRole,
    VisualBeat,
    VisualBeatDraft,
    VisualBeatPhase,
    VisualExecutionContract,
    VisualShot,
    VoiceRequirement,
)

__all__ = (
    "ArtifactEnvelope",
    "ArtifactKind",
    "AudioEvent",
    "BlockingBeat",
    "BlockingBeatDraft",
    "BlockingCommit",
    "BlockingDraft",
    "CanonicalTimeline",
    "DecisionBasis",
    "DecisionDraft",
    "DPReviewVerdict",
    "DeterministicGateResult",
    "DirectorDecision",
    "DomainValidationError",
    "EpisodeDirectionDraft",
    "ExecutionDesignDraft",
    "FactKind",
    "FactRegistry",
    "FactSemantic",
    "GenerationSegment",
    "GenerationSegmentTimeline",
    "IdFactory",
    "IndependentDPReviewResult",
    "KnowledgeCapsuleV2",
    "KnowledgeCandidateRecord",
    "KnowledgeCapabilityScope",
    "KnowledgeDecisionEntry",
    "KnowledgeDecisionView",
    "KnowledgeSnapshot",
    "KnowledgeStage",
    "MediaEvidence",
    "OwnerApprovalDecision",
    "OwnerApprovalRecord",
    "ProjectionAST",
    "ProjectionManifest",
    "ProjectionNode",
    "ReferenceRequirement",
    "SceneIntentDraft",
    "ScriptFact",
    "ShotBoundary",
    "ShotDesignDraft",
    "SourceRef",
    "StoryboardRole",
    "TickRange",
    "TimelinePlacement",
    "ValidationStatus",
    "VisualBeat",
    "VisualBeatDraft",
    "VisualBeatPhase",
    "VisualCurvePoint",
    "VisualCurvePointDraft",
    "VisualExecutionContract",
    "VisualShot",
    "VoiceRequirement",
)
