
import os
Q = chr(34)
N = chr(10)

lines = []
lines.append('#!/usr/bin/env python3')
lines.append('"""script_assembler.py v1.0 - deterministic MODE:P script assembler"""')
lines.append('import yaml, re, argparse, sys')
lines.append('')
lines.append('# Constants')
lines.append('PFAL_G=["no frame txt","no mm","no pupil","no sub-sec"]')
lines.append('PFAL_CU=["no face drift"]; PFAL_WS=["max2 audio"]')
lines.append('PFAL_DLG=["no 2+ mouth"]; PFAL_SCR=["no rendered txt"]')
lines.append('PFAL_MOV=["no limb deform"]; PFAL_WIN=["no flicker"]')
lines.append('REF={("D","WS"):"@bar_wide",("D","MS"):"@bar_mid",("D","CU"):"@bar_cu",("D","ECU"):"@bar_ecu",("B","CU"):"@window_cu",("A","MS"):"@door_mid",("C","WS"):"@mid_wide",("ST","CU"):"@street_cu"}')
lines.append('MODEL={("CU",0):"Jimeng4",("MS",0):"Jimeng4/VEO",("WS",0):"Kling/VEO",("MS",1):"Hailuo"}')
lines.append('LIGHT={"A":"L1+L4","B":"L2+L5","C":"L4+L2mix","D":"L3+L4(Rembrandt)","AD":"L1->L3grad","ST":"ext5500K"}')
lines.append('CH={"#1":[],"#2":["I"],"#3":[],"#4":["I"],"#5":["S"],"#6":["I","S"],"#7":["I"],"#8":[],"#9":["R"],"#10":["I"],"#11":["R","I"],"#12":["R"],"#13":["I"],"#14":["R"],"#15":[],"#16":["B"],"#17":["I","R"],"#18":[]}')
lines.append('DLG_S={"#6","#10","#12","#13","#14","#15","#17"}')
lines.append('')
lines.append('# Helpers')
lines.append('def ly(p):')
lines.append('    with open(p,encoding="utf-8") as f: d=yaml.safe_load(f)')
lines.append('    return d.get("scene",{}), d.get("global_anchors",{}), d.get("time_skeleton",[])')
lines.append('def zone(pos):')
lines.append('    if "A" in pos: return "AD" if ("bar" in pos.lower() or "counter" in pos.lower()) else "A"')
lines.append('    for z in ["B","C","D"]:')
lines.append('        if z in pos: return z')
lines.append('    return "D"')
lines.append('def stk(st):')
lines.append('    if "te" in st or "jin" in st: return "CU"')
lines.append('    if "zhong" in st: return "MS"')
lines.append('    if "quan" in st: return "WS"')
lines.append('    return "MS"')
lines.append('def wc(t): return len(re.sub(r"[\s,.;:?!()]","",t))')
lines.append('')
print(f'Generated {len(lines)} lines so far')
with open("D:/JianyingPro/tsc/导演系统_v5/01_调度器/script_assembler.py", "w", encoding="utf-8") as f:
    f.write(N.join(lines))
